references="https://en.wikipedia.org/wiki/List_of_supermarket_chains_in_the_United_States"

pharmacy_map = {'ACME Sav-On':'grocery',
 'AHF Pharmacy' :'retail',
 'Accredo Therapeutics':'retail',
 'Acme Markets Pharmacy':'grocery',
 'Albertsons':'grocery',
 'Albertsons (Osco)':'grocery',
 'Albertsons (Sav-on)':'grocery',
 'Albertsons Market':'grocery',
 'Amigos Pharmacy':'retail',
 'Aurora Pharmacy':'retail',
 'Bakers Pharmacy':'grocery',
 'Bartell Drug Co':'retail',
 'Bashas Pharmacy':'grocery',
 'Bel Air Pharmacy':'grocery',
 'Benzer Pharmacy':'retail',
 'Bi-Lo Pharmacy':'grocery',
 'Bi-Mart Pharmacy':'grocery',
 'Big Y Foods Pharmacy':'grocery',
 'Brookshire Brothers':'grocery',
 'Brookshires Pharmacy':'grocery',
 'CVS (Schnucks)':'grocery',
 'CVS Pharmacy':'retail',
 'Carepoint Pharmacy':'retail',
 'Carilion Clinic Pharmacy':'retail',
 'Carrs Pharmacy':'grocery',
 'CaryRx - Free Same-Day Rx Delivery':'retail',
 'City Market':'grocery',
 'Community, a Walgreens Pharmacy':'retail',
 'Copps':'retail',
 'Costco':'grocery',
 'Cub Foods Pharmacy':'grocery',
 'Dierbergs Pharmacy':'retail',
 'Dillons Pharmacy':'grocery',
 'Discount Drug Mart':'retail',
 'Duane Reade':'retail',
 'Essentia Health':'retail',
 'Farm Fresh Pharmacy':'grocery',
 'Floresta Pharmacy':'retail',
 'Food City Pharmacy':'grocery',
 'Food Lion Pharmacy':'grocery',
 'Fred Meyer Pharmacy':'grocery',
 'Freds Pharmacy':'retail',
 'Fresco y Mas':'retail',
 'Froedtert Pharmacy':'retail',
 'Fruth Pharmacy':'retail',
 'Frys Pharmacy':'grocery',
 'Gerbes Pharmacy':'grocery',
 'Giant Eagle Pharmacy':'grocery',
 'Giant Pharmacy':'grocery',
 'Good Day Pharmacy':'retail',
 'HEB Grocery':'retail',
 'Haggen':'grocery',
 'Hannaford Brothers Pharmacy':'grocery',
 'Harris Teeter':'grocery',
 "Harvey's Supermarket":'grocery',
 'Horton & Converse Pharmacy':'retail',
 'Hy-Vee':'grocery',
 'Intermountain Healthcare Pharmacy':'retail',
 'JayC':'grocery',
 'Jewel-Osco':'grocery',
 'King Soopers':'grocery',
 'Kinney Drug':'retail',
 'Kmart':'grocery',
 'Kroger Pharmacy':'grocery',
 'Lewis Drug':'retail',
 'Longs':'retail',
 'Lucky Pharmacy':'retail',
 "Marc's":'retail',
 "Mariano's":'retail',
 'Market Street Pharmacy':'retail',
 'Marsh Drugs':'retail',
 'Martins':'retail',
 'MedCart Specialty Pharmacy':'retail',
 'Medicine Shoppe':'retail',
 'Meijer Pharmacy':'grocery',
 'Metro Market':'retail',
 'Minyard Pharmacy':'retail',
 'Navarro Discount Pharmacy':'retail',
 'Nob Hill':'retail',
 'Owens':'retail',
 'Pavilions Pharmacy':'retail',
 'Pay Less Super Market Pharmacy':'grocery',
 'Pharmaca Integrative Pharmacy':'retail',
 "Pick 'n Save":'retail',
 'Prescription Drug Foundation':'retail',
 'Price Chopper':'grocery',
 'Price Cutter':'grocery',
 'Providence Family Pharmacy':'retail',
 'Publix':'grocery',
 'QFC':'grocery',
 "Raley's":'grocery',
 'Ralphs':'grocery',
 "Randall's":'grocery',
 'Rite Aid':'retail',
 'Rite Aid (Walgreens)':'retail',
 'Ritzman Pharmacy':'retail',
 'Safeway':'grocery',
 'Sams Club':'grocery',
 'Sav-Mor':'grocery',
 'Sav-on':'grocery',
 'Save Mart Pharmacy':'grocery',
 'Shaws':'grocery',
 'Shop N Save Pharmacy':'grocery',
 'ShopRite':'grocery',
 'Shopko':'grocery',
 'Shoppers Pharmacy':"grocery",
 "Smith's":'retail',
 'Stop n Shop':'grocery',
 'Super 1 Pharmacy':'retail',
 'Target (CVS)':'grocery',
 'The Pharmacy at Piggly Wiggly Athens':'retail',
 'Thrifty White Pharmacy':'retail',
 'Tom Thumb Pharmacy':'retail',
 'Tops Pharmacy':'grocery',
 'United Pharmacy':'retail',
 'University of Utah Health':'retail',
 'Vistara Pharmacy':'retail',
 'Vons Pharmacy':'grocery',
 'Walgreens':'retail',
 'Walgreens Specialty Pharmacy':'retail',
 'Walmart':'grocery',
 'Walmart Neighborhood Market':'grocery',
 'Warren Care Pharmacy':'retail',
 'Wegmans':'grocery',
 'Weis Pharmacy':'retail',
 'Winn-Dixie':'grocery',
 'Yamato Pharmacy':'retail',
               'nan':'unknown',
"Omnicare" :"retail", # Check
"Mercy Pharmacy":"retail",# Check
"Harps Pharmacy":"retail",# Check
"Avita Pharmacy":"retail",# Check
"Cigna Health":"retail",# Check
"Genoa Healthcare":"retail",# Check
"Humana Pharmacy":"retail",# Check
"Ingles Pharmacy":"retail",# Check
"Kroger Specialty":"retail",# Check
"Harmons Pharmacy":"retail", # Check
               
"Dedicated Senior Medical":"retail"   #check           
               
               }